### ISSUE TITLE
Changing the wait parameter from rapidParam

### ISSUE THREAD

**Issue by jagraterol** [nicolasmcnair/magpy#10]
Hello,

first for making this toolbox. I have a question, is there a way or changing the "wait" parameter from the rapidParam dict? Somehow mine shows 0.1 and not even the recommended 0.5 s of wait time between trains

**Comment by nicolasmcnair** [comment]
Hi there. Unfortunately, there aren't any instructions in the communication
protocol document from Magstim about how to change the Wait time. I haven't
checked if it simply sets it to the required minimum given whatever the
current stimulation parameters are. I will reach out to them to see if
there's an updated copy.

**Comment by jagraterol** [comment]
I got a copy of the communication protocol a few days ago and it's on rev 5. I don't know if it's the same you have and as you said, there is no information about changing the waiting period. If I understand correctly, that's the time it waits between trains of whatever frequency one chooses, right? 

For example, if select 10 Hz trains for 3 seconds, then I would need 3.2 seconds of a task to account for those 0.1 between the stimuli. Did I understand this correctly?

**Comment by nicolasmcnair** [comment]
I have revision 5.3. If you have a later one I'd really appreciate grabbing
a copy from you.

As for wait time, yes that's correct - except I think the minimum wait time
is 1s? You can check that in the GUI interface on the Rapid machine itself.
If you enter in your parameters it will then tell you what the minimum wait
time must be.

**Comment by jagraterol** [comment]
We have the same version of the protocol.
