### ISSUE TITLE
stuck at connect()  function

### ISSUE THREAD

**Issue by jackypiaa** [nicolasmcnair/magpy#4]
hello~
Thanks for developing this toolbox
I have some problems that I always stuck at the connect() function 
Here is the code : 

from magpy import magstim

if __name__ == "__main__":
    myMagstim = magstim.Rapid('COM7')
    print(1)
    myMagstim.connect()
    print(2)
    errorCode,parameterInfo = myMagstim.getParameters()
    myMagstim.arm(delay=True)
    myMagstim.fire()
    myMagstim.disconnect()

and it's result : 
1

it's stuck at connect but I don't know why
Would you please help me?
Thanks!

**Comment by nicolasmcnair** [comment]
Hi there. Is this a new Rapid system? If so, it will also require a unique unlock code that can only be obtained from Magstim directly (see the section under 'Usage' [here](https://github.com/nicolasmcnair/magpy)). You can check which version you have in the settings menu in the UI.

**Comment by jackypiaa** [comment]
Thanks for replying,
My Rapid2’s version is 8.0.
I’m checking if there is any problem on USB to COM cable.

**Comment by nicolasmcnair** [comment]
Hi, just wanted to check whether you had resolved this issue or not?

**Comment by jagraterol** [comment]
Hi, I know some time has passed, but I presume that I am having the same issue. 
When I run the `myMagstim.connect()` command it gets stuck. It neither returns the prompt nor throws an exception. I am trying to run the code under Windows 10.

We tested the cable and some simple code on a Debian machine and it works. So the problem might be OS-related. I tried running the miniconda prompt as admin and still nothing. Do you have any ideas for where to look?

**Comment by nicolasmcnair** [comment]
Sorry for the late response. I'm currently putting together a version of
MagPy which will log everything happening with the serial port - which
should make problems like this easier/possible to diagnose. I'll try and
get a working version to you as soon as I am able.

**Comment by jagraterol** [comment]
Hey! Thanks for your answer. I solved connecting issue. I usually try new things with jupyter lab. Somehow Python kept connected to the COM port after I closed the session. When I started testing again it just hung and wasn't throwing any errors. I found out what was happening and had to kill the Python service. This happened on Windows 10. Perhaps this info can help someone in the future.

**Comment by nicolasmcnair** [comment]
Great! Thanks for letting me know!
