### ISSUE TITLE
_virtual module missing

### ISSUE THREAD

**Issue by victoris93** [nicolasmcnair/magpy#7]
Hi,

I'm new to TMS and to magpy, so the following might be a trivial issue. I need to set up TMS triggers using a virtual Magstim Rapid device. I executed the following:

 ```
from magpy import magstim
from time import sleep

if __name__ == "__main__":
	myTMS = magstim.Rapid('virtual')
	myTMS.connect()
	errorCode,parameterInfo = myTMS.getParameters()
```
Which yielded the following error:

```
Traceback (most recent call last):
  File "tms.py", line 5, in <module>
    myTMS = magstim.Magstim('virtual')
  File "/Users/VictoriaShevchenko/opt/anaconda3/lib/python3.8/site-packages/magpy/magstim.py", line 339, in __init__
    self._setupSerialPort(serialConnection)
  File "/Users/VictoriaShevchenko/opt/anaconda3/lib/python3.8/site-packages/magpy/magstim.py", line 350, in _setupSerialPort
    from _virtual import virtualPortController
ModuleNotFoundError: No module named '_virtual'
```
How come the module is missing? _virtual.py is in the package directory.

Thanks in advance!

**Comment by nicolasmcnair** [comment]
Apologies for the late reply. _virtual was removed as I did not have time to update it with the rest of the package. I would like to reimplement it at some point in the future.
